version: '3.8'
services:
  app:
    image: 192.168.0.191:5000/spur/backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://admin:admin@192.168.0.191:5432/test?schema=public
    ports:
      - '3001:3001'
